# Generated by Django 3.2.8 on 2021-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='아이디')),
                ('pw', models.CharField(max_length=50, verbose_name='비밀번호')),
                ('isAdmin', models.BooleanField(verbose_name='관리자여부')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('userDept', models.CharField(max_length=50, verbose_name='부서')),
                ('phone', models.CharField(max_length=50, verbose_name='전화번호')),
            ],
        ),
    ]
