# Generated by Django 3.2.8 on 2021-10-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.CharField(error_messages={'unique': '해당 아이디가 이미 존재합니다.'}, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='아이디')),
                ('pw', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('isAdmin', models.BooleanField(verbose_name='관리자여부')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('dept', models.CharField(max_length=100, verbose_name='부서명')),
                ('phone', models.CharField(max_length=100, verbose_name='전화번호')),
            ],
        ),
    ]
