# Generated by Django 3.2.8 on 2021-10-09 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptNo', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True, verbose_name='부서 번호')),
                ('deptName', models.CharField(max_length=50, verbose_name='부서명')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='userDept',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(error_messages={'unique': '해당 아이디가 이미 존재합니다.'}, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='아이디'),
        ),
        migrations.AddField(
            model_name='user',
            name='deptNo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='userAuth.dept'),
        ),
    ]
