# Generated by Django 3.2.8 on 2021-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_userrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRequest',
        ),
        migrations.AddField(
            model_name='user',
            name='isConfirmed',
            field=models.BooleanField(default=0, verbose_name='승인여부'),
        ),
    ]
