# Generated by Django 3.2.8 on 2021-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0002_auto_20211009_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='deptNo',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='부서 번호'),
        ),
    ]
