# Generated by Django 3.2.8 on 2021-10-27 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_auto_20211015_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='최근로그인'),
            preserve_default=False,
        ),
    ]
