# Generated by Django 3.2.8 on 2021-10-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_alter_dept_deptno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(error_messages={'unique': '해당 아이디가 이미 존재합니다.'}, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(max_length=100, verbose_name='비밀번호'),
        ),
    ]
