# Generated by Django 3.2.8 on 2021-10-31 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_user_lastlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lastLogin',
        ),
        migrations.AddField(
            model_name='user',
            name='joinDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='가입일자'),
            preserve_default=False,
        ),
    ]
