# Generated by Django 3.2.8 on 2021-10-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=100, verbose_name='신청자')),
                ('what', models.IntegerField(verbose_name='신청품목')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('type', models.BooleanField(verbose_name='유형')),
                ('confirmedBy', models.CharField(max_length=100, null=True, verbose_name='승인자')),
                ('comment', models.TextField(verbose_name='코멘트')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='품목명')),
                ('cls', models.CharField(max_length=100, verbose_name='분류')),
                ('stock', models.IntegerField(verbose_name='재고수량')),
                ('image', models.FileField(upload_to='', verbose_name='이미지')),
            ],
        ),
    ]
